### PR TITLE
Update to create-react-app v4

### PR DESCRIPTION
**Pull request by akronb**
Updated dependencies:
- `react-scripts 4.0.3`
- `react 17.0.2`
- `eslint 7.32`
- `@storybook/xxx 6.1`

Some of `eslint` plugins and configs were removed from package.json, because they're already built-in into `react-scripts`.

I've replaced the depreciated rules and disabled new ones. From version 4 `react-scripts build` exits when code has some eslint errors, so I turned on all rules that cause error as a warning.

### CODE REVIEW

**Review by howardchung — APPROVED** [review]

**Comment by howardchung** [comment]
Looks like a netlify CI error?

**Comment by akronb** [comment]
Yeah, I bumped minimal `node` version to v16 (active LTS version), so maybe node v10 causing the error.

I deployed this branch to Netlify myself, and it looks okay, here is [deploy log](https://app.netlify.com/sites/lucid-visvesvaraya-4dfe21/deploys/62338c40ecf769007c1e56c1) and [site](https://62338c40ecf769007c1e56c1--lucid-visvesvaraya-4dfe21.netlify.app/).

**Comment by howardchung** [comment]
I don't know if we can specify it specifically, netlify offers several build images and I tried updating to latest but it still seems to fail

**Comment by akronb** [comment]
@howardchung It's alive!

I added CI configuration file to repo and changed `node` version for build. You can move this configuration in netlify settings if you want.

**Pull request merged**
