### PR TITLE
Enable Fade-in when choosing hero in Combo page 

### PR DESCRIPTION
**Pull request by jzhao62**
Enable Fade-in when choosing heros into teamA teamB in combo page. 
- try to enable fade out, but it requres refactor the deselectHero function
-fix some linting erros

### CODE REVIEW

**Comment by howardchung** [comment]
lgtm

**Comment by Argn0** [comment]
I think the transition time should be shorter. 1 second feels too slow.

**Comment by jzhao62** [comment]
yeah, 1 sec is a little bit too slow, I will modify that with my next PR

**Comment by howardchung** [comment]
@jzhao62 do you just want to update this one?

**Comment by jzhao62** [comment]
I made fade-out partially works, could be on a different PR, or if you want to wait

**Comment by Argn0** [comment]
We can wait, there is no rush.

**Comment by howardchung** [comment]
I think if you want to make that change it should just be on this PR rather than opening another

**Pull request closed without merging**
