### PR TITLE
[RELEASE] 2022-07-12 Subscriptions

### PR DESCRIPTION
**Pull request by albertcui**
In order to keep the site running, automatic match parsing is now a [subscriber](https://www.opendota.com/subscribe) feature. You can continue to manually [request](https://www.opendota.com/request) matches for parsing. To learn more about this change, check out the [blog post](https://blog.opendota.com/2022/07/11/subscribe/).

Thank you for your continued support.

### CODE REVIEW

**Comment by Dikzamen** [comment]
I am playing using several accounts. If I subscribe can I request automatic match parsing for all accounts?

**Comment by howardchung** [comment]
Each subscription can only be linked to one account.

**Comment by Dikzamen** [comment]
Thank you

**Comment by OperationalDev** [comment]
Does this have any impact on API calls?

**Comment by howardchung** [comment]
Fewer matches will be parsed automatically, otherwise no. In the future, we may need to put a limit on the number of calls to /request per account.

**Pull request merged**
