### PR TITLE
Updated Captains Mode Ban Order

### LINKED ISSUE #1602: Captains Mode Ban Order
**Current Behavior**
The second phase bans if viewing a captains mode match are listed in the old order, with first pick getting the second and fourth ban of the phase, and second pick getting the first and third

**Expected behavior/code**
The order got flipped in 7.15 to second pick having the second and fourth ban of the second phase, and first pick having the first and third

**Console Output**
Doesn't apply

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
https://imgur.com/Zf2AmEQ incorrect order

### PR DESCRIPTION
**Pull request by akshatmittal**
Fixed the ban order for matches. Currently figuring out if it would be possible to show the previous order pre-7.15.

### CODE REVIEW

**Comment by howardchung** [comment]
You can use the match date or patch number to determine which order to show

**Comment by howardchung** [comment]
https://github.com/odota/dotaconstants/blob/master/build/patch.json#L138

**Comment by akshatmittal** [comment]
Now shows the order based on the patch. Also, I've used a static timestamp for the patch time although I could directly fetch it from the Dota constants and convert to appropriate format although I see no benefit in doing that.

(Also sorry for the delay, I was away)

**Comment by akshatmittal** [comment]
I've resolved the conflicts and is now in sync with latest.

**Pull request merged**
