### PR TITLE
more skeleton loaders

### PR DESCRIPTION
**Pull request by Phrynobatrachus**
continues work on #1407, covers what @howardchung mentioned except for the login widget. I'm going to work on cleaning up the rest tomorrow.

### CODE REVIEW

**Comment by howardchung** [comment]
were there tweaks you wanted to make?

**Comment by Phrynobatrachus** [comment]
sorry been afk with rl work, getting started on swapping the hero page spinners which I think is mostly it. also if you have a preference on how these should be organized let me know, maybe I should put them in a folder like spinner?

**Comment by howardchung** [comment]
Yeah, I think it makes sense to put all the loader components in a directory.

**Comment by howardchung** [comment]
Also I think the gray looks better than the purple

**Comment by Argn0** [comment]
Did removing the animations from the skeleton loaders actually resolve the performance issues?

**Pull request merged**
