### PR TITLE
remove dotacoach, update rivalry

### LINKED ISSUE #2289: remove dotacoach links
DotaCoach is no longer maintained. We should remove the buttons.

### PR DESCRIPTION
**Pull request by albertcui**
fixes #2289

### CODE REVIEW

**Comment by howardchung** [comment]
couple errors @albertcui

**Comment by howardchung** [comment]
I don't think you need to remove eslint. What was the issue with it?

**Comment by albertcui** [comment]
````
> react-scripts build
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.
The react-scripts package provided by Create React App requires a dependency:
  "eslint": "5.6.0"
Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:
  /home/travis/build/odota/web/node_modules/eslint (version: 5.16.0) 
Manually installing incompatible versions is known to cause hard-to-debug issues.
If prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.
To fix the dependency tree, try following the steps below in the exact order:
  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "eslint" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.
In most cases, this should be enough to fix the problem.
````

**Comment by howardchung** [comment]
Try resetting all your changes to package and package-lock? This change should not require any package updates.

**Pull request merged**
