### PR TITLE
1488 heroabilities

### LINKED ISSUE #1488: show ability information on hero pages
Add more information to each hero's `heroes/#` page

- Spells and their information (mana cost, description, etc.)
- Commonly purchased items and their win rates

This could be built out as new tabs or pages, or it could even just be a large link to one of the Wiki pages

___

Along the same vein, it would also be good to have a link to each hero's page on the match overview tab. Even something as simple as wrapping the hero's portrait in a link

### PR DESCRIPTION
**Pull request by bdbch**
This will fix #1488.

I added the abilities to the hero page and implemented tooltips for the representive data.

### CODE REVIEW

**Comment by bdbch** [comment]
bildschirmfoto 2018-06-16 um 00 53 09
bildschirmfoto 2018-06-16 um 00 53 15

There we go

**Comment by howardchung** [comment]
we should consider reusing the same component for the tooltips on the overview page:
https://deploy-preview-1625--opendota-stage.netlify.com/matches/3945533175

**Comment by bdbch** [comment]
@howardchung alright. I'll refactor that one.

**Comment by bdbch** [comment]
@howardchung feel free to merge this.

I refactored the tooltip from the `inflictorWithValue.jsx` into it's own `ThingTooltip` which now can be used whenever we need to show a Tooltip for a `Thing` (Skills or Items).

Feel free, I think we're finished.

**Comment by bdbch** [comment]
I also tweaked the general Item tooltip btw and added the gold costs to the `resources` group.

image

image

image

**Pull request merged**
