### PR TITLE
Hide stray hero icons on Buildings Map in Overview tab

### PR DESCRIPTION
**Pull request by Argn0**

### CODE REVIEW

**Comment by howardchung** [comment]
isn't this the map that we want the icons on?

**Comment by Argn0** [comment]
it's this one in Overview 
overviewmap

**Comment by howardchung** [comment]
Yes, isn't that the map we want to show the icons on?  I don't think we actually show them anywhere else.

**Comment by Argn0** [comment]
That's weird...What's the purpose of those icons? What do those positions represent?

**Comment by Argn0** [comment]
Must be laning. I misunderstood the icons. I thought that map is only supposed to show the destroyed buildings .

**Comment by howardchung** [comment]
Maybe we should retitle the map

**Pull request closed without merging**
