### PR TITLE
Adjust larger font-size for TabBar component.

### PR DESCRIPTION
**Pull request by hungvt13**
Since the additional tabs are added to the TabBar making the text hard to view. I adjusted it so that they are more visible. Also I kept the same font size for small screen devices.

### CODE REVIEW

**Comment by howardchung** [comment]
I believe my primary reason for the font size change was to avoid the tabs running onto two lines:
https://deploy-preview-1989--opendota-stage.netlify.com/matches/4260113474

**Comment by hungvt13** [comment]
Hello Howard, on my laptop it's all on one line, also the resolution is 1280 x 800. I tested a range of widths and the tabs will eventually running running into two lines unless we make use of calc().
screen shot 2018-12-09 at 19 58 48

**Comment by howardchung** [comment]
I think on 1920 x 1080 it goes two lines.  I think we should try for getting it on one line for that (it's the most common resolution) and not worry about smaller viewports.

**Comment by howardchung** [comment]
does #1998 somewhat resolve this?

**Comment by Argn0** [comment]
> does #1998 somewhat resolve this?

In my opinion it does.

**Pull request closed without merging**
