### PR TITLE
Combos page: display results in the exact same order as selection

### PR DESCRIPTION
**Pull request by Argn0**
Before:
dd2

After:
ddw

### CODE REVIEW

**Comment by howardchung** [comment]
Do you think this is better for usability? I kind of like preserving the order from the match

**Comment by Argn0** [comment]
> Do you think this is better for usability? I kind of like preserving the order from the match

Yes, this is something that has bothered me personally. I believe it is much clearer this way.

**Comment by Argn0** [comment]
> Do you think this is better for usability? I kind of like preserving the order from the match

Also isn't the order from the match random anyway and has no meaning?

**Comment by Argn0** [comment]
One advantage is that you can much easier see the other heroes in the match that were not selected.

**Pull request merged**
