### PR TITLE
Add new ranked tier icons and stars

### PR DESCRIPTION
**Pull request by moonrobin**
From game files. Note rank_star_0 denotes uncalibrated player.

### CODE REVIEW

**Comment by howardchung** [comment]
I don't think we need the 0 star image?

**Comment by howardchung** [comment]
Also is there one for "uncalibrated/0"?

**Comment by howardchung** [comment]
Maybe rename rank_star_0 to rank_icon_0 if we are using it for players with a 0 value

**Comment by moonrobin** [comment]
I missed a file when I was going through it the first time. Went back and found the uncalibrated rank icon.

**Comment by howardchung** [comment]
It would also be cool to have some documentation on how these files were extracted (make a wiki page or something?)

**Comment by moonrobin** [comment]
Added a new [wiki page](https://github.com/odota/web/wiki/Extracting-image-assets-from-game-client).

**Comment by moonrobin** [comment]
Hey @howardchung can this PR go through?

**Comment by howardchung** [comment]
Sure, but did you want to include the changes to display the icons on profiles in this PR?

**Comment by howardchung** [comment]
I merged the PR since @GravityMsc is planning to add this

**Comment by howardchung** [comment]
Looks like there are 6 and 7 star tiers now.

**Pull request merged**
