### PR TITLE
Testcafe Example

### PR DESCRIPTION
**Pull request by Phrynobatrachus**
This is a quick example for #1596 using Testcafe. The second test in the file is probably closer to what we're looking for, if the goal is just to run through available routes. I suppose the third is more #144? Anyways I figured I'd post this PR for anyone who might be interested in working on either of those issues.

### CODE REVIEW

**Comment by howardchung** [comment]
Thanks. I believe @Argn0 also has a branch with testcafe included, perhaps we can integrate that with this tests?

**Comment by Luchanso** [comment]
Can you look on [puppeteer](https://github.com/GoogleChrome/puppeteer) too?

**Comment by Argn0** [comment]
Does anyone know why you can't do named imports in the test1.js file?

like if I wanted to do ```import { isRadiant } from '../src/utility';``` it doesnt work.

**Comment by Argn0** [comment]
and if you do ```import transformMatch from '../src/actions/transformMatch';``` it imports transformMatch but then it can't import utility in transformMatch.

**Comment by Phrynobatrachus** [comment]
@Luchanso I probably will try it out, but Testcafe looks like it might be easier to integrate with BrowserStack, and it supports running tests through FF as well.

**Comment by howardchung** [comment]
I think we can combine this with https://github.com/odota/web/pull/1804 which is similar

**Pull request closed without merging**
