### PR TITLE
updated ranked icons

### PR DESCRIPTION
**Pull request by moonrobin**
Also updated the wiki page for Valve's first party Resource Viewer tool.

### CODE REVIEW

**Comment by howardchung** [comment]
Thanks!  Do we know what the criteria is for displaying the 7a, 7b, 7c icons?

@GravityMsc is planning to work on updating the code to display icons.

**Comment by GravityMsc** [comment]
`api/players/xxxxxx` shows 3 kinds of rank number: competitive_rank, solo_competitive_rank, leaderboard_rank. Maybe I gues I only need leaderboard_rank, is it right?

And... I'm going to know the 7a icon. In my opinion, 7b means Top 100, 7c means Top 10.

**Comment by howardchung** [comment]
yeah competitive/solo_competitive are party/solo MMR that aren't in the client anymore.  We still return the last known value.

**Comment by GravityMsc** [comment]
OK, I still need an example to explain the 7a icon.
7c: No.10 -- 1
7b: NO.100 -- 11
7a: ? maybe its rank tier is 76 and have the leaderboard_rank number?

And Chinese rank tier transitions will be fixed in the future.

**Comment by howardchung** [comment]
Yeah, I guess 76 outside the top 100 makes sense for 7a.

**Pull request merged**
