### PR TITLE
[RELEASE] 2017-11-30

### PR DESCRIPTION
**Pull request by howardchung**
* Added toggle to show/hide small purchases on purchases tab (@Argn0 )
* Fixed padding issue on damage crosstables (@Argn0)
* Updated visuals on match log tab (@Argn0)
* Added service worker for Progressive Web App support (@superoo7 )
* Fixed a Chinese translation (@GravityMsc )
* Updated dotaconstants data for new valve item names (@coreymaher )
* Replaced MMR on match pages with rank tier (@warchildmd)
* Hero rankings have been reset and are testing a new ranking algorithm (@howardchung)

### CODE REVIEW

**Comment by purebe** [comment]
MMR should still be visible on the match page, bad change.

**Comment by howardchung** [comment]
The data will get less and less accurate over time, so in my opinion it's better to not show it than show inaccurate values.

**Comment by purebe** [comment]
I just saw they removed mmr entirely, well rip.  Will opendota consider tracking their own mmr at some point in the future?

**Comment by howardchung** [comment]
probably not since not all players expose public match data.

**Comment by purebe** [comment]
i hate this game

**Pull request merged**
