### PR TITLE
#2184

### PR DESCRIPTION
**Pull request by slavabelb**
Functionality #2184

### CODE REVIEW

**Comment by howardchung** [comment]
Thanks, I think this will work but it should be possible to do this with Recharts config options to reduce the amount of code necessary? Haven't had a chance to investigate yet.

**Comment by slavabelb** [comment]
@howardchung So we are using BarChar (http://recharts.org/en-US/api/BarChart) as Histogram. So i found nothing in props that can help reduce amount of code

**Comment by howardchung** [comment]
Maybe we could do the transform in TrendGraph/HistogramGraph instead? I like the idea of keeping the original units in the data model and only transforming it at display time.

**Comment by howardchung** [comment]
I think for TrendGraph we can use the tickFormatter on the YAxis component:
http://recharts.org/en-US/api/YAxis#tickFormatter

**Pull request closed without merging**
