### PR TITLE
Added Dota Plus badge to player profiles

### PR DESCRIPTION
**Pull request by builder-247**
As per https://github.com/odota/core/pull/1865.

### CODE REVIEW

**Comment by howardchung** [comment]
Do you have a sample player ID with plus to see how this looks once core is deployed to production?

**Comment by builder-247** [comment]
> Do you have a sample player ID with plus to see how this looks once core is deployed to production?

Here: `115042342`.

**Comment by builder-247** [comment]
@howardchung how often does the mmr service run per user usually? I've only tested that the function doing the data population works, so it might take a while to update.

**Comment by howardchung** [comment]
Should be after each ranked match

**Comment by howardchung** [comment]
I still think it looks too big, but open to opinions

**Comment by builder-247** [comment]
Yeah looking at it again I have to agree

**Comment by howardchung** [comment]
https://deploy-preview-2044--opendota-stage.netlify.com/players/115042342

Looks a bit squished?

**Comment by Argn0** [comment]
width must be 65px for the correct image ratio.

**Comment by builder-247** [comment]
oops I didn't notice the ratio wasn't 1:1,

**Pull request merged**
