### PR TITLE
Added button to toggle starting items on overview

### PR DESCRIPTION
**Pull request by 27bslash**

### CODE REVIEW

**Comment by howardchung** [comment]
Does this require the corresponding backend change to preview?

In general though I feel that we should keep the overview as simple as possible. Maybe we can put this on another tab?

**Comment by 27bslash** [comment]
Here's an image of the changes:

image

If the replay is not parsed the starting items button does not show up.

image

**Comment by Argn0** [comment]
I don't like this button from an aesthetic point of view.

**Comment by Argn0** [comment]
Also the starting items are already in the Items tab

**Comment by 27bslash** [comment]
The starting items in the items tab are inaccurate, it does not account for shared items, sold items or item charges:
image
each one of these should have 2 sets of tangos for example.

Also the button is the same as the show consumables button from the items tab, I tried to play it safe and re-use an existing element. Do you have any suggestions on how to change it?

**Comment by Argn0** [comment]
I suggest fixing the items tab instead so it displays the starting items correctly.

**Pull request closed without merging**
