### PR TITLE
Implement counts record on Overview Tab.

### LINKED ISSUE #771: counts summary section on overview
I'm thinking we can display some of the counts data (abbreviated) on the Overview page.  Category data like:
* radiant/dire and winrate on each
* most played gamemode and winrate
* winrate and matches played in most recent patch
* top 3 regions and winrate

We can make the counts API call (like we do for peers, heroes, and matches) and then just display a subset of the data.

### PR DESCRIPTION
**Pull request by covertPZ**
fixes #771 
Increased number of heroes in order to make the page alignment look cleaner.
Logic may not be the best, so definitely looking for some review/optimization. (had some difficulty understanding the transforms that were occurring to the data and why certain fields weren't accessible at certain stages in processing)
Container title probably deserves a better name, or at least it's own variable if we decide to change it in the future.

### CODE REVIEW

**Comment by howardchung** [comment]
tip: If you make your branch on this repo it's easier for the rest of us to clone without having to add your repo to remote :)

**Comment by howardchung** [comment]
General comments:
* Currently seems a bit buried (user has to scroll down a lot).  Could we maybe move to a three column layout?
* Probably should separate the sections (radiant/dire, patch, region, mode)
* Context links to the matches filter page when number is clicked on (like heroes/players?)  More generally this could be done for the rest of the counts

**Comment by covertPZ** [comment]
Ah, okay. I'll create the branches on the main repo from now on. Will make my workflow easier too :)

The three column layout makes things look super busy and will only get more filled if the counts get split into individual tables. This layout is also pushing it to show content without horizontal scrolling (below 1540px the counts would need to be pushed down) 
image

Maybe we want to represent this data similar to the "Summary" section?

**Comment by blukai** [comment]
> Currently seems a bit buried (user has to scroll down a lot). Could we maybe move to a three column layout?

I think that 3 columns is bad

> - Context links to the matches filter page when number is clicked on (like heroes/players?) More generally this could be done for the rest of the counts
> - Instead of a table, maybe something a little more eye-catching? c3 has gauge charts: http://c3js.org/samples/chart_gauge.html or maybe donut charts: http://c3js.org/samples/chart_donut.html

👍

**Comment by howardchung** [comment]
Yeah, maybe another row under the summary section would be good

**Comment by covertPZ** [comment]
Still working out some parts of this, but before I go much further I'd like some feedback.
image

**Comment by howardchung** [comment]
Maybe we could shorten the last 20 games summary and put them both on one line?  IMO having two additional rows on top is pushing down the "primary" content a little.

**Comment by howardchung** [comment]
I wonder if it would make sense to put this section under the existing content, rather than over.

**Comment by howardchung** [comment]
replaced by #1635

**Pull request closed without merging**
